version: "3.8"

services:
  orientdb-node1:
    image: orientdb:latest
    container_name: orientdb-node1
    command: "dserver.sh"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpassword
      - ORIENTDB_NODE_NAME=node1
    volumes:
      - ./databases/node1:/orientdb/databases 
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/orientdb-dserver-config.xml:/orientdb/config/orientdb-dserver-config.xml
      - ./data:/orientdb/data
    network_mode: "host"
  orientdb-node2:
    image: orientdb:latest
    container_name: orientdb-node2
    command: "dserver.sh"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpassword
      - ORIENTDB_NODE_NAME=node2
    volumes:
      - ./databases/node2:/orientdb/databases
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/orientdb-dserver-config.xml:/orientdb/config/orientdb-dserver-config.xml
    network_mode: "host"